---

- name: restart the os
  become: yes
  ansible.builtin.reboot:

# The UI takes a bit to load. Just having an SSH connection isn't enough.
- name: sleep for 1 minute
  wait_for: timeout=60
  delegate_to: localhost
